language: java
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email: false
deploy:
  provider: openshift
  user: "woodyc40@gmail.com"
  password: "TheSGDev"
  domain: "https://openshift.redhat.com/broker/rest/domains/tsg-sgdevteam"
  skip_cleanup: true