language: java
jdk:
  - oraclejdk7
notifications:
  email: false
deploy:
  provider: openshift
  user: "woodyc40@gmail.com"
  password: "TheSGDev"
  domain: "sgdevteam/applications/tsg"
  skip_cleanup: true
