language: java
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email: false
deploy:
  provider: openshift
  user: "woodyc40@gmail.com"
  password: "TheSGDev"
  domain: "openshift.redhat.com/broker/rest/domains/tsg-sgdevteam/applications/The-Survival-Games"
  skip_cleanup: true