name: The Survival Games
main: me.theepicbutterstudios.thesurvivalgames.TheSurvivalGames
version: 1.0.0
author: The Community!
#database: true  Uncomment once Quantum64 adds the SQL database

commands:
    sg: 
        usage: /sg <command>
        description: You don't need any other commands since the CommandHandler handles the rest
        aliases: [survival-games, sgames]

permissions:
    sg.*:
        description: Allows you to run EVERY LAST SG COMMAND!
        children:
            sg.admin
            sg.mod
            sg.player
# Rest Indev
